# Generated by Django 2.2.7 on 2020-02-11 13:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ieltsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signdate', models.DateField(default=datetime.date(2020, 2, 11), verbose_name='打卡时间')),
                ('buqianstatus', models.BooleanField(default=False, verbose_name='是否补签')),
                ('wordnumber', models.IntegerField(default=0, verbose_name='单词背诵数量')),
                ('readpercent', models.IntegerField(default=0, verbose_name='阅读正确率')),
                ('listenpercent', models.IntegerField(default=0, verbose_name='听力正确率')),
                ('wordimageset', models.TextField(blank=True, null=True, verbose_name='单词图片')),
                ('readimageset', models.TextField(blank=True, null=True, verbose_name='阅读图片')),
                ('writeimageset', models.TextField(blank=True, null=True, verbose_name='写作图片')),
                ('listenimageset', models.TextField(blank=True, null=True, verbose_name='听力图片')),
                ('speakimageset', models.TextField(blank=True, null=True, verbose_name='口语图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '雅思打卡',
                'verbose_name_plural': '雅思打卡',
            },
        ),
    ]
