# Generated by Django 2.2.7 on 2020-02-12 08:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltsmodel',
            name='signdate',
            field=models.DateField(default=datetime.date(2020, 2, 12), verbose_name='打卡时间'),
        ),
        migrations.CreateModel(
            name='toeflModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signdate', models.DateField(default=datetime.date(2020, 2, 12), verbose_name='打卡时间')),
                ('buqianstatus', models.BooleanField(default=False, verbose_name='是否补签')),
                ('wordnumber', models.IntegerField(default=0, verbose_name='单词背诵数量')),
                ('readpercent', models.IntegerField(default=0, verbose_name='阅读正确率')),
                ('listenpercent', models.IntegerField(default=0, verbose_name='听力正确率')),
                ('wordimageset', models.TextField(blank=True, null=True, verbose_name='单词图片')),
                ('readimageset', models.TextField(blank=True, null=True, verbose_name='阅读图片')),
                ('writeimageset', models.TextField(blank=True, null=True, verbose_name='写作图片')),
                ('listenimageset', models.TextField(blank=True, null=True, verbose_name='听力图片')),
                ('speakimageset', models.TextField(blank=True, null=True, verbose_name='口语图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '托福打卡',
                'verbose_name_plural': '托福打卡',
            },
        ),
        migrations.CreateModel(
            name='greModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signdate', models.DateField(default=datetime.date(2020, 2, 12), verbose_name='打卡时间')),
                ('buqianstatus', models.BooleanField(default=False, verbose_name='是否补签')),
                ('wordnumber', models.IntegerField(default=0, verbose_name='单词背诵数量')),
                ('fill_blank_number', models.IntegerField(default=0, verbose_name='填空题正确率')),
                ('readpercent', models.IntegerField(default=0, verbose_name='阅读正确率')),
                ('mathpercent', models.IntegerField(default=0, verbose_name='数学正确率')),
                ('wordimageset', models.TextField(blank=True, null=True, verbose_name='单词图片')),
                ('readimageset', models.TextField(blank=True, null=True, verbose_name='阅读图片')),
                ('writeimageset', models.TextField(blank=True, null=True, verbose_name='写作图片')),
                ('mathimageset', models.TextField(blank=True, null=True, verbose_name='数学图片')),
                ('fill_blank_imageset', models.TextField(blank=True, null=True, verbose_name='填空图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'gre打卡',
                'verbose_name_plural': 'gre打卡',
            },
        ),
        migrations.CreateModel(
            name='gmatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signdate', models.DateField(default=datetime.date(2020, 2, 12), verbose_name='打卡时间')),
                ('buqianstatus', models.BooleanField(default=False, verbose_name='是否补签')),
                ('wordnumber', models.IntegerField(default=0, verbose_name='单词背诵数量')),
                ('grammarnumber', models.IntegerField(default=0, verbose_name='语法正确率')),
                ('readpercent', models.IntegerField(default=0, verbose_name='阅读正确率')),
                ('mathpercent', models.IntegerField(default=0, verbose_name='数学正确率')),
                ('logicpercent', models.IntegerField(default=0, verbose_name='逻辑正确率')),
                ('wordimageset', models.TextField(blank=True, null=True, verbose_name='单词图片')),
                ('readimageset', models.TextField(blank=True, null=True, verbose_name='阅读图片')),
                ('grammarimageset', models.TextField(blank=True, null=True, verbose_name='语法图片')),
                ('writeimageset', models.TextField(blank=True, null=True, verbose_name='写作图片')),
                ('mathimageset', models.TextField(blank=True, null=True, verbose_name='数学图片')),
                ('logicimageset', models.TextField(blank=True, null=True, verbose_name='逻辑图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'gmat打卡',
                'verbose_name_plural': 'gmat打卡',
            },
        ),
    ]
