# Generated by Django 2.2.10 on 2020-02-19 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200212_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmatmodel',
            name='signdate',
            field=models.DateField(default=datetime.date(2020, 2, 19), verbose_name='打卡时间'),
        ),
        migrations.AlterField(
            model_name='gremodel',
            name='signdate',
            field=models.DateField(default=datetime.date(2020, 2, 19), verbose_name='打卡时间'),
        ),
        migrations.AlterField(
            model_name='ieltsmodel',
            name='signdate',
            field=models.DateField(default=datetime.date(2020, 2, 19), verbose_name='打卡时间'),
        ),
        migrations.AlterField(
            model_name='toeflmodel',
            name='signdate',
            field=models.DateField(default=datetime.date(2020, 2, 19), verbose_name='打卡时间'),
        ),
    ]
