# Generated by Django 2.2.7 on 2020-02-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/UserProFilebg/avatar/%y/%d/154f5429806e45c286fe7fcfe818652e'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='media/UserProFilebg/%Y/%m/154f5429806e45c286fe7fcfe818652e', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('2', '女'), ('1', '男')], default='1', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='cf09332db4e94d7d9bae2733271ffb95', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
