# Generated by Django 2.2.10 on 2020-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendusers', '0003_auto_20200212_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_bh',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/UserProFilebg/avatar/%y/%d/6abc019dc633495ab8b474b9fe1c4c14'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='media/UserProFilebg/%Y/%m/6abc019dc633495ab8b474b9fe1c4c14', verbose_name='背景图'),
        ),
    ]
