# Generated by Django 3.0.4 on 2020-03-11 12:04

import backendusers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendusers', '0004_auto_20200219_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.CharField(default=backendusers.models.createuuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('del_state', models.IntegerField(choices=[(0, '已删除'), (1, '默认')], db_index=True, default=1, verbose_name='删除状态')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('wechat_name', models.CharField(max_length=50, verbose_name='微信名')),
                ('system_role', models.IntegerField(choices=[(0, '普通用户'), (1, '管理员')], default=0, verbose_name='系统角色')),
                ('school', models.CharField(blank=True, max_length=200, null=True, verbose_name='学校')),
                ('grade', models.CharField(blank=True, max_length=30, null=True, verbose_name='多少届')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/UserProFilebg/avatar/%y/%d/835ba80e5dca4242a54b201e92c39906'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='media/UserProFilebg/%Y/%m/835ba80e5dca4242a54b201e92c39906', verbose_name='背景图'),
        ),
    ]
