# Generated by Django 3.0.4 on 2020-03-14 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendusers', '0005_auto_20200311_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='微信用户'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/UserProFilebg/avatar/%y/%d/1587a8cb9eb4488fa1e594b17cf3edcd'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='media/UserProFilebg/%Y/%m/1587a8cb9eb4488fa1e594b17cf3edcd', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('2', '女'), ('1', '男')], default='1', max_length=10, verbose_name='性别'),
        ),
    ]
