# Generated by Django 3.0.4 on 2020-05-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendusers', '0006_auto_20200314_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendusers.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '教师'), (2, '管理员')], default=0, verbose_name='系统角色'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/UserProFilebg/avatar/%y/%d/3b14fba5f2554ee68cdd1cb94184e470'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='media/UserProFilebg/%Y/%m/3b14fba5f2554ee68cdd1cb94184e470', verbose_name='背景图'),
        ),
    ]
